[log]
level = "debug"
fpath = "./logs/go-logger"
msize = 2000  
mage = 7     
mbackup = 5 

[server]
port = ":8080"

### [코드리뷰]
# config 파일 내에 개발과 운영의 차이를 두지 않는 것은 좋은 코드 습관입니다.
# 해당 코드는 환경변수로 관리하며, 코드에서 환경변수를 불러와 사용하는 것을 추천드립니다.
###