definitions:
  controller.Controller:
    type: object
info:
  contact: {}
paths:
  /orderer/v01/menus:
    get:
      consumes:
      - application/json
      description: 메뉴 조회 기능
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Controller'
      summary: call GetMenus, return ok by json.
  /orderer/v01/order:
    post:
      consumes:
      - application/json
      description: 주문 기능
      parameters:
      - description: phone
        in: body
        name: phone
        required: true
        schema:
          type: string
      - description: address
        in: body
        name: address
        required: true
        schema:
          type: string
      - description: menuName
        in: body
        name: menuName
        required: true
        schema:
          items:
            type: string
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Controller'
      summary: call CreateOrder, return ok by json.
  /orderer/v01/order/{id}:
    patch:
      consumes:
      - application/json
      description: 주문을 추가하는 기능
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Controller'
      summary: call AddOrder, return ok by json.
    put:
      consumes:
      - application/json
      description: 주문 수정 기능
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Controller'
      summary: call AddOrder, return ok by json.
  /orderer/v01/order/state:
    get:
      consumes:
      - application/json
      description: 주문 상태 조회 기능
      parameters:
      - description: phone
        in: query
        name: phone
        required: true
        type: string
      - description: address
        in: query
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Controller'
      summary: call GetOrderState, return ok by json.
  /orderer/v01/reviews:
    get:
      consumes:
      - application/json
      description: 리뷰 조회 기능
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Controller'
      summary: call GetReviews, return ok by json.
  /orderer/v01/reviews/{orderId}:
    post:
      consumes:
      - application/json
      description: 리뷰 기능
      parameters:
      - description: orderId
        in: path
        name: orderId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Controller'
      summary: call CreateReview, return ok by json.
  /receipient/v01/menus:
    post:
      consumes:
      - application/json
      description: 메뉴 추가 가능
      parameters:
      - description: name
        in: body
        name: name
        required: true
        schema:
          type: string
      - description: canBeOrder
        in: body
        name: canBeOrder
        required: true
        schema:
          type: boolean
      - description: quantity
        in: body
        name: quantity
        required: true
        schema:
          type: integer
      - description: price
        in: body
        name: price
        required: true
        schema:
          type: integer
      - description: origin
        in: body
        name: origin
        required: true
        schema:
          type: string
      - description: todayRecommend
        in: body
        name: todayRecommend
        required: true
        schema:
          type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Controller'
      summary: call NewMenu, return ok by json.
  /receipient/v01/menus/{name}:
    delete:
      consumes:
      - application/json
      description: 메뉴 삭제 기능
      parameters:
      - description: name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Controller'
      summary: call DeleteMenu, return ok by json.
    patch:
      consumes:
      - application/json
      description: 메뉴 업데이트 가능
      parameters:
      - description: name
        in: path
        name: name
        required: true
        type: string
      - description: canBeOrder
        in: body
        name: canBeOrder
        required: true
        schema:
          type: boolean
      - description: price
        in: body
        name: price
        required: true
        schema:
          type: integer
      - description: origin
        in: body
        name: origin
        required: true
        schema:
          type: string
      - description: todayRecommend
        in: body
        name: todayRecommend
        required: true
        schema:
          type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Controller'
      summary: call UpdateMenu, return ok by json.
  /receipient/v01/order:
    get:
      consumes:
      - application/json
      description: 주문 조회 기능
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Controller'
      summary: call GetOrders, return ok by json.
  /receipient/v01/order/{id}/state:
    patch:
      consumes:
      - application/json
      description: 주문 상태 업데이트 기능
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Controller'
      summary: call UpdateOrderState, return ok by json.
swagger: "2.0"
